### ISSUE TITLE
Repository improvements

### ISSUE THREAD

**Issue by dmitr1sdae** [etoyadadaya/manga-server#1]
# [manga-server](https://github.com/etoyadadaya/manga-server)
- Delete [.idea](https://github.com/etoyadadaya/manga-server/tree/master/.idea)
- Add .gitignore to root directory
- Add readme.md
- Move [roles-guard.ts](https://github.com/etoyadadaya/manga-server/blob/master/server/src/auth/roles-guard.ts) to the guards folder

**Comment by etoyadadaya** [comment]
- [X] Delete [.idea](https://github.com/etoyadadaya/manga-server/tree/master/.idea)
- [X] Add .gitignore to root directory
- [X] Add readme.md
- [X] Move [roles-guard.ts](https://github.com/etoyadadaya/manga-server/blob/master/server/src/auth/roles-guard.ts) to the guards folder
